# Generated by Django 2.1.5 on 2019-01-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190126_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
