# Generated by Django 2.1.5 on 2019-01-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190126_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Fecha publicación',
            new_name='pubDate',
        ),
    ]
